eCondition = {
    1: "Bring Object to Area",
    2: "Bring Object to Object",
    3: "Own Objects",
    4: "Own Fewer Objects",
    5: "Objects in Area",
    6: "Destroy Object",
    7: "Capture Object",
    8: "Accumulate Attribute",
    9: "Research Tehcnology",
    10: "Timer",
    11: "Object Selected",
    12: "AI Signal",
    13: "Player Defeated",
    14: "Object Has Target",
    15: "Object Visible",
    16: "Object Not Visible",
    17: "Researching Technology",
    18: "Units Garrisoned",
    19: "Difficulty Level",
    20: "Own Fewer Foundations",
    21: "Selected Objects in Area",
    22: "Powered Objects in Area",
    23: "Units Queued Past Pop Cap"
}
