eTile = {
    0: "Grass 1 (default terrain)",
    1: "Water, Shallow",
    2: "Beach (no buildings)",
    3: "Dirt 3 (grassy)",
    4: "Shallows",
    5: "Leaves",
    6: "Dirt 1 (brown with occasional cactus)",
    7: "Farm",
    8: "Dead Farm",
    9: "Grass 3 (brownish)",
    10: "Forest",
    11: "Dirt 2 (dirt grass mixture)",
    12: "Grass 2 (lush / very green)",
    13: "Palm Desert",
    14: "Desert (sandy and light colored)",
    15: "Water (not dockable)",
    16: "Looks like Grass 1 (can build, only siege can move)",
    17: "Jungle",
    18: "Bamboo",
    19: "Pine Forest",
    20: "Forest (says oak forest when clicking tree)",
    21: "Snow Pine Forest",
    22: "Water, Deep",
    23: "Water, Medium",
    24: "Road",
    25: "Road, Broken",
    26: "Ice (no ships)",
    27: "Dirt 2 (no beach, building residue, dockable)",
    28: "Water, Bridge (walkable, no ships)",
    29: "Farm 1",
    30: "Farm 2",
    31: "Farm 3",
    32: "Snow",
    33: "Snow Dirt",
    34: "Snow Grass",
    35: "Ice (allows ships)",
    36: "Snow Dirt (building residue)",
    37: "Ice, Beach (allows ships, build walls only)",
    38: "Road, Snow",
    39: "Road, Fungus",
    40: "Rock / Road (no buildings)",
    41: "Looks like grass 1 (nobuild, crazy pathfinding, black on map)"
}
